In [25]:
import requests
import pandas as pd
import time

BASE_URL = "https://product.kt.com/wDic/getOptionItemListAjax.ajax"
HEADERS = {"User-Agent": "Mozilla/5.0"}


def fetch_page(cate_code, filter_code, option_code, page_no, list_size=10):
    params = {
        "cate_code": cate_code,
        "pageNo": page_no,
        "listSize": list_size,
        "filter_code": filter_code,
        "option_code": option_code,
    }
    resp = requests.get(BASE_URL, params=params, headers=HEADERS)
    resp.raise_for_status()
    return resp.text


def crawl_all_pages(cate_code, filter_code, option_code, list_size=10, max_pages=50, sleep_sec=0.3):
    all_dfs = []
    page_no = 1

    while page_no <= max_pages:
        html = fetch_page(cate_code, filter_code, option_code, page_no, list_size)
        df = parse_kt_plan_list(html)

        if df.empty:
            break

        df["page"] = page_no
        all_dfs.append(df)
        page_no += 1
        time.sleep(sleep_sec)

    if not all_dfs:
        return pd.DataFrame()
    return pd.concat(all_dfs, ignore_index=True)


df = crawl_all_pages(cate_code="6002", filter_code="191", option_code="260")
df

C:\Users\NT551_11TH\AppData\Local\Temp\ipykernel_23476\3329661429.py:40: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_dfs, ignore_index=True)

,carrier,plan_name,monthly_fee,monthly_fee_discounted,item_code,page
0,KT,초이스 더블,120000.0,81600.0,1691,1
1,KT,초이스,90000.0,61200.0,1681,1
2,KT,베이직,28900.0,19651.0,1693,1
3,KT,베이직(이월),37000.0,25160.0,1694,1
4,KT,음성,12100.0,8228.0,1697,1
5,KT,요고 모바일,30000.0,NaN,1567,1
6,KT,키즈,13000.0,8840.0,1695,1
7,KT,웰컴,39000.0,26520.0,1577,1
8,KT,스마트기기,16500.0,NaN,1696,1
9,KT,데이터투게더,11000.0,NaN,1698,1
10,KT,듀얼번호,8800.0,NaN,1540,2
11,KT,순 완전무한(3G),56100.0,NaN,1013,2
12,KT,순 모두다올레(3G),30800.0,NaN,1014,2
13,KT,순 청소년(3G),25300.0,NaN,1017,2
14,KT,순 골든(3G),22000.0,NaN,1018,2
15,KT,순 나눔(3G),25300.0,NaN,1016,2
16,KT,순 i(3G),23100.0,NaN,1015,2
17,KT,신 표준,13200.0,NaN,12,2
18,KT,표준 요금제,12100.0,NaN,7,2
19,KT,슬림,10450.0,NaN,35,2
20,KT,3G 효 요금제,9680.0,NaN,38,3
21,KT,키즈 알115(3G),12650.0,NaN,955,3
22,KT,Style 요금제,19800.0,NaN,36,3
23,KT,알스마트,20900.0,NaN,48,3
24,KT,알캡요금제,15400.0,NaN,8,3
25,KT,골든스마트 요금제,16500.0,NaN,279,3
26,KT,손말 요금제,15400.0,NaN,31,3
27,KT,복지15000 요금제,16500.0,NaN,25,3
28,KT,LTE 선불,NaN,NaN,1036,3
29,KT,LTE 웰컴_선불(외국인 전용),35000.0,NaN,1612,3
30,KT,3G 선불,NaN,NaN,1038,4
31,KT,순 데이터(3G),13750.0,NaN,1019,4
32,KT,Wearable(3G),8800.0,NaN,988,4
33,KT,키즈 80,8800.0,NaN,1067,4

In [ ]:
import time

BASE_URL = "https://product.kt.com"
HEADERS = {"User-Agent": "Mozilla/5.0"}


def resolve_detail_url(item_code, cate_code, filter_code, option_code, page_size=10):
    if item_code is None:
        return None

    item_url = (
        f"{BASE_URL}/wDic/productDetail.do"
        f"?ItemCode={item_code}&CateCode={cate_code}"
        f"&filter_code={filter_code}&option_code={option_code}&pageSize={page_size}"
    )
    html_text = requests.get(item_url, headers=HEADERS).text

    match = re.search(r'(htmlUploadType_\d+\.html)', html_text)
    if not match:
        return None

    return f"{BASE_URL}/static/prodetail/{item_code}/web/{match.group(1)}"


def add_detail_urls(df, cate_code, filter_code, option_code, sleep_sec=0.3):
    urls = []
    for code in df["item_code"]:
        urls.append(resolve_detail_url(code, cate_code, filter_code, option_code))
        time.sleep(sleep_sec)
    df["detail_url"] = urls
    return df


df = add_detail_urls(df, cate_code="6002", filter_code="191", option_code="260")
df

,carrier,plan_name,monthly_fee,monthly_fee_discounted,item_code,page,detail_url
0,KT,초이스 더블,120000.0,81600.0,1691,1,https://product.kt.com/static/prodetail/1691/w...
1,KT,초이스,90000.0,61200.0,1681,1,None
2,KT,베이직,28900.0,19651.0,1693,1,None
3,KT,베이직(이월),37000.0,25160.0,1694,1,https://product.kt.com/static/prodetail/1694/w...
4,KT,음성,12100.0,8228.0,1697,1,https://product.kt.com/static/prodetail/1697/w...
5,KT,요고 모바일,30000.0,NaN,1567,1,None
6,KT,키즈,13000.0,8840.0,1695,1,None
7,KT,웰컴,39000.0,26520.0,1577,1,https://product.kt.com/static/prodetail/1577/w...
8,KT,스마트기기,16500.0,NaN,1696,1,None
9,KT,데이터투게더,11000.0,NaN,1698,1,https://product.kt.com/static/prodetail/1698/w...
10,KT,듀얼번호,8800.0,NaN,1540,2,None
11,KT,순 완전무한(3G),56100.0,NaN,1013,2,https://product.kt.com/static/prodetail/1013/w...
12,KT,순 모두다올레(3G),30800.0,NaN,1014,2,https://product.kt.com/static/prodetail/1014/w...
13,KT,순 청소년(3G),25300.0,NaN,1017,2,None
14,KT,순 골든(3G),22000.0,NaN,1018,2,https://product.kt.com/static/prodetail/1018/w...
15,KT,순 나눔(3G),25300.0,NaN,1016,2,https://product.kt.com/static/prodetail/1016/w...
16,KT,순 i(3G),23100.0,NaN,1015,2,https://product.kt.com/static/prodetail/1015/w...
17,KT,신 표준,13200.0,NaN,12,2,https://product.kt.com/static/prodetail/12/web...
18,KT,표준 요금제,12100.0,NaN,7,2,None
19,KT,슬림,10450.0,NaN,35,2,None
20,KT,3G 효 요금제,9680.0,NaN,38,3,None
21,KT,키즈 알115(3G),12650.0,NaN,955,3,None
22,KT,Style 요금제,19800.0,NaN,36,3,https://product.kt.com/static/prodetail/36/web...
23,KT,알스마트,20900.0,NaN,48,3,None
24,KT,알캡요금제,15400.0,NaN,8,3,None
25,KT,골든스마트 요금제,16500.0,NaN,279,3,https://product.kt.com/static/prodetail/279/we...
26,KT,손말 요금제,15400.0,NaN,31,3,None
27,KT,복지15000 요금제,16500.0,NaN,25,3,None
28,KT,LTE 선불,NaN,NaN,1036,3,https://product.kt.com/static/prodetail/1036/w...
29,KT,LTE 웰컴_선불(외국인 전용),35000.0,NaN,1612,3,None
30,KT,3G 선불,NaN,NaN,1038,4,https://product.kt.com/static/prodetail/1038/w...
31,KT,순 데이터(3G),13750.0,NaN,1019,4,https://product.kt.com/static/prodetail/1019/w...
32,KT,Wearable(3G),8800.0,NaN,988,4,None
33,KT,키즈 80,8800.0,NaN,1067,4,None

In [31]:
df[[ "plan_name", "detail_url"]]

            plan_name                                         detail_url
0              초이스 더블  https://product.kt.com/static/prodetail/1691/w...
1                 초이스                                               None
2                 베이직                                               None
3             베이직(이월)  https://product.kt.com/static/prodetail/1694/w...
4                  음성  https://product.kt.com/static/prodetail/1697/w...
5              요고 모바일                                               None
6                  키즈                                               None
7                  웰컴  https://product.kt.com/static/prodetail/1577/w...
8               스마트기기                                               None
9              데이터투게더  https://product.kt.com/static/prodetail/1698/w...
10               듀얼번호                                               None
11         순 완전무한(3G)  https://product.kt.com/static/prodetail/1013/w...
12        순 모두다올레(3G)  https://product.kt.com/static/prodetail/1014/w...
13          순 청소년(3G)                                               None
14           순 골든(3G)  https://product.kt.com/static/prodetail/1018/w...
15           순 나눔(3G)  https://product.kt.com/static/prodetail/1016/w...
16            순 i(3G)  https://product.kt.com/static/prodetail/1015/w...
17               신 표준  https://product.kt.com/static/prodetail/12/web...
18             표준 요금제                                               None
19                 슬림                                               None
20           3G 효 요금제                                               None
21        키즈 알115(3G)                                               None
22          Style 요금제  https://product.kt.com/static/prodetail/36/web...
23               알스마트                                               None
24              알캡요금제                                               None
25          골든스마트 요금제  https://product.kt.com/static/prodetail/279/we...
26             손말 요금제                                               None
27        복지15000 요금제                                               None
28             LTE 선불  https://product.kt.com/static/prodetail/1036/w...
29  LTE 웰컴_선불(외국인 전용)                                               None
30              3G 선불  https://product.kt.com/static/prodetail/1038/w...
31          순 데이터(3G)  https://product.kt.com/static/prodetail/1019/w...
32       Wearable(3G)                                               None
33              키즈 80                                               None

In [53]:
detail_soup = BeautifulSoup(detail_html, 'html.parser')

In [54]:
detail_soup

<div class="inner">
<div class="location">
<script type="text/javascript">
    if(window.location.pathname.includes("productDetail.do")){
        kt.locationBar();
    }
</script>
</div>
<div class="N-cHead-section">
<div class="N-cHead-column">
<div class="N-cHeadline-cover">
<h1 class="N-cHeadline">초이스<br/>
더블</h1>
<div class="N-head-btn-section">
<div class="N-head-btn-column sns"><button class="opener" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^공유하기');" type="button"><img alt="공유하기" src="/static/prodetail/N_version/web/images/common/icon_N_sns.png"/></button>
<div class="N-head-btn-area"><a class="icon kakao" href="javascript:void(0);" onclick="sns.gokakao('1691','폰케어 초이스'); KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^공유하기_카카오톡');" title="새창열림">카카오톡</a><a class="icon facebook" href="javascript:void(0);" onclick="sns.goFaceBook('폰케어 초이스','https://product.kt.com/wDic/productDetail.do?ItemCode=1691'); KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^공유하기_페이스북');" title="새창열림">페이스북</a><a class="icon twitter" href="javascript:void(0);" onclick="sns.goTwitter('폰케어 초이스','https://product.kt.com/wDic/productDetail.do?ItemCode=1691'); KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^공유하기_트위터');" title="새창열림">트위터</a><a class="icon naverline" href="javascript:void(0);" onclick="sns.goLine('폰케어 초이스','https://product.kt.com/wDic/productDetail.do?ItemCode=1691'); KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^공유하기_라인');" title="새창열림">라인</a></div>
</div>
<div class="N-head-btn-column more"><button class="opener" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^상품더보기');" type="button"><img alt="상품더보기" src="/static/prodetail/N_version/web/images/common/icon_N_more.png"/></button>
<div class="N-head-btn-area"><a href="https://product.kt.com/wDic/productDetail.do?ItemCode=1682" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^상품더보기_초이스_티빙/지니/밀리');">초이스 티빙/지니/밀리</a><a href="https://product.kt.com/wDic/productDetail.do?ItemCode=1687" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^상품더보기_초이스_삼성');">초이스 삼성</a><a href="https://product.kt.com/wDic/productDetail.do?ItemCode=1688" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^기본정보^상품더보기_초이스_디바이스');">초이스 디바이스</a></div>
</div>
</div>
</div>
<div class="N-picode-com-age-benefit" data-pktcode-js="age-benefit"><span class="N-pdt-com-icon">덤 혜택</span>
<div aria-label="연령별 혜택 선택" class="N-picode-com-age-benefit-btn-group" role="tablist"><button aria-selected="true" class="btn-column" data-age="base" role="tab" type="button">기본제공</button><button aria-selected="false" class="btn-column" data-age="y" role="tab" type="button">Y덤(만 19세 ~ 만 34세)</button><button aria-selected="false" class="btn-column" data-age="65" role="tab" type="button">65+덤(만 65세 ~ 만 74세)</button><button aria-selected="false" class="btn-column" data-age="75" role="tab" type="button">75+덤(만 75세 ~)</button></div>
</div>
<div class="N-cSummry"><span class="N-pdt-com-icon">공통혜택</span>
<ul class="N-cSummry-list">
<li><img alt="" class="img" src="https://product.kt.com/static/prodetail/N_version/common/images/icon/icon_N_csummry_info1.png"/> 데이터 무제한</li>
<li><img alt="" class="img" src="https://product.kt.com/static/prodetail/N_version/common/images/icon/icon_N_csummry_info2.png"/> 초이스 혜택 2개</li>
</ul>
</div>
</div>
<div class="N-picode-com-compare-wrap">
<div class="N-pdt-compare-section">
<div class="swiper-wrapper">
<div class="N-pdt-compare-column swiper-slide"><strong class="name">디즈니플러스+ 폰케어</strong>
<p class="month">월 <span class="price">120,000</span>원<span class="add-copy">(부가세포함)</span></p>
<p class="price-summary"><span class="add-copy">선택약정 할인 시 90,000원</span> <span class="price-column">월 <span class="price">81,600</span>원</span> <span class="add-copy sale"><img alt="% 할인" src="/static/prodetail/1485/common/images/icon/icon_percent_sale.png"/><span class="line-tt">7% 다이렉트 요금할인 시</span></span></p>
<div class="btn-group"><a class="btn-column" href="https://my.kt.com/product/MobilePriceView.do?ctgryProd=PL265P970" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스 더블^요금제비교^디즈니플러스+_폰케어_신청하기');">신청하기</a><a class="btn-column add1" href="https://shop.kt.com/pc/smart/allProdCallCounseling.do?prodNo=WL00076862" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_디즈니 더블^요금제비교^디즈니플러스+_폰케어_7%_할인_기변_상담');">7% 할인 기변 상담</a></div>
<ul class="detail-list">
<li class="logo-column"><img alt="Disney" class="logo" src="/static/prodetail/N_version/web/images/d/w_logo_N_pdt_info_d_20240402.png"/><img alt="" class="logo" src="/static/prodetail/1521/common/images/N_head_logo_phonecare_choice.png"/></li>
<li><strong class="tit">로밍데이터 무제한</strong><span class="point-mint">최대 100Kbps 속도제어</span></li>
<li><strong class="tit">멤버십 혜택</strong><span class="point-mint">VVIP 혜택</span></li>
<li><strong class="tit">단말 보험 월정액 멤버십 할인</strong> 월 최대 4,500원</li>
<li><strong class="tit">스마트기기</strong><span class="point-mint">1회선 무료</span></li>
<li><strong class="tit">데이터 쉐어링</strong><span class="point-mint">1회선 무료</span></li>
<li data-pktcode-js="share-data" data-share-idx="disneyPhocare"><strong class="tit">스마트기기/테더링 공유데이터</strong><span class="point-mint"><img alt="" class="icon" src="/static/prodetail/common/images/icons/member_dum/default_dum_18x18.png"/>기본혜택</span>90GB</li>
</ul>
</div>
<div class="N-pdt-compare-column swiper-slide img-column-tp1"><img alt="Coming SOON 새로운 혜택을 준비 중에 있습니다." class="img-center" src="/static/prodetail/1691/web/itemForte/images/banner/w_comming_soon_tt.png"/> <img alt="" src="/static/prodetail/1691/web/itemForte/images/banner/w_comming_soon_btm.png"/></div>
</div>
</div>
</div>
</div>
<ul class="N-pdt-noted-list">
<li>데이터 쉐어링 및 스마트기기 전용 요금제 할인 혜택은 대리점/고객센터를 통해 별도 신청 시 제공됩니다. <a aria-label="가입 및 유의사항으로 이동" class="pduct-btn-is-line" href="#" id="N-pdt-acc-move" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^상단_유의문구^데이터쉐어링_자세히보기');" role="button">자세히 보기</a></li>
<li>7% 추가 할인은 다이렉트샵에서 휴대폰 구매 및 가입(기기변경, 신규, 번호이동) 또는 유심 가입(신규, 번호이동) 시 제공되는 혜택이며, 단순 요금제 변경 시에는 적용되지 않습니다.</li>
</ul>
<h2 class="picode-m-heading" style="margin:57px 0 0 0;"><span class="bold-tt">두 가지 혜택을 하나의 요금제로, 초이스 더블</span></h2>
<h3 class="picode-1674-c-heading"><img alt="혜택 하나!" class="icon-pfinger" src="/static/prodetail/1674/web/itemForte/images/icon/w_icon_pfinger_01.png"/> <span class="line star">디즈니+ <span class="bold">콘텐츠 무제한 시청</span> <img alt="" class="icon-star" src="/static/prodetail/1674/common/itemForte/images/icon/icon_star.png"/></span></h3>
<div class="picode-1674-top-banner"><img alt="Disney+" src="/static/prodetail/1674/web/itemForte/images/banner/w_banner_disney.png"/><button class="btn" data="N-accordion-move" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^본문^디즈니+_이용방법');" type="button"><span class="is-hidden">디즈니+ 이용방법</span></button></div>
<h4 class="picode-1674-s-heading">디즈니+ 상품안내</h4>
<table class="picode-1674-tbl">
<caption class="invisible">디즈니+ 상품안내 표, 상품 구분, 영상화질, 오디오, 동시 시청 가능 수, 콘텐츠 저장, 이용기기 등으로 구성함</caption>
<colgroup>
<col style="width:16%;"/>
<col style="width:16%;"/>
<col style="width:16%;"/>
<col style="width:16%;"/>
<col style="width:16%;"/>
<col style="width:16%;"/>
</colgroup>
<thead>
<tr>
<th scope="col">상품 구분</th>
<th scope="col">영상화질</th>
<th scope="col">오디오</th>
<th scope="col">동시 시청 가능 수</th>
<th scope="col">콘텐츠 저장</th>
<th scope="col">이용기기</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">디즈니+ 프리미엄</th>
<td>최대 4K UHD &amp; HDR</td>
<td>최대 Dolby Atmos 오디오</td>
<td>4</td>
<td>가능</td>
<td rowspan="2">스마트폰, 태블릿, PC, 크롬캐스트, 안드로이드TV, 애플TV, 스마트TV(삼성,LG)</td>
</tr>
<tr>
<th scope="row">디즈니+ 스탠다드</th>
<td>최대 1080p Full HD</td>
<td>최대 5.1 사운드</td>
<td>2</td>
<td class="brline-tp0">가능</td>
</tr>
</tbody>
</table>
<ul class="picode-1674-dot-list">
<li>디즈니+ 상품은 TV를 포함한 모든 디바이스에서 시청이 가능합니다.</li>
<li>디즈니+ 상품별 제공하는 영상 화질/오디오 및 저장 기능은 인터넷 서비스, 기기 성능, 멤버십 유형 및 각 콘텐츠에 따라 달라질 수 있습니다. 각 콘텐츠별 다양한 기능 표시가 있을 수 있으나, 해당 멤버십 유형에서 사용 가능한 최대 사양까지만 이용할 수 있습니다.<a class="N-pdt-btn-is" href="https://www.disneyplus.com/ko-kr" target="_blank" title="새창열림">자세히보기</a></li>
<li>본 요금제는 디즈니+ 스탠다드 상품을 기본 제공합니다.
	<ul class="picode-1674-desh-list">
<li>디즈니+ 스탠다드 상품은 디즈니+ 프리미엄 상품으로 변경 가능하며, 요금제 월정액 외 추가 요금 4,000원이 나옵니다. (월 중 변경 시, 이용 일수 만큼 요금 청구)</li>
<li>디즈니+ 스탠다드/프리미엄 상품 간 변경은 월 1회 가능합니다. (신청 경로 : 마이 &gt; 요금/서비스 &gt; 요금제 변경 &gt; 디즈니플러스+ 폰케어 초이스 더블 옵션 설정)</li>
</ul>
</li>
</ul>
</div>
<div class="picode-1674-fte-bg-column">
<div class="picode-1674-fte-area">
<h3 class="picode-1674-c-heading"><img alt="혜택 둘!" class="icon-pfinger" src="/static/prodetail/1674/web/itemForte/images/icon/w_icon_pfinger_02.png"/> <span class="line star">365 폰케어 <span class="bold">단말 보험 할인</span> <img alt="" class="icon-star" src="/static/prodetail/1674/common/itemForte/images/icon/icon_star.png"/></span></h3>
<div class="picode-1674-btn-groups"><a class="picode-1674-btn-column" href="https://product.kt.com/wDic/productDetail.do?ItemCode=1604" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_5G_초이스_더블^본문^365_폰케어_단말_보험_상품_상세_내용_확인_및_신청하기');">365 폰케어 단말 보험 상품 상세 내용 확인 및 신청하기</a></div>
<table class="N-pdt-choice-tbl">
<caption class="invisible">단말보험상품 안내 표, 할인 대상 상품, 보상범위, 가입 가능 단말 및 출고가, 월ㅈ정액, 초이스 할인 후, 멤버십 포인트 할인 시 등으로 구성험.</caption>
<colgroup>
<col style="width:14%;"/>
<col style="width:14%;"/>
<col style="width:14%;"/>
<col style="width:14%;"/>
<col style="width:14%;"/>
<col style="width:14%;"/>
<col style="width:14%;"/>
</colgroup>
<thead>
<tr>
<th colspan="2" scope="col">할인 대상 상품</th>
<th scope="col">보상<br/>
			범위</th>
<th scope="col">가입 가능<br/>
			단말 및 출고가</th>
<th scope="col">월정액</th>
<th scope="col">초이스 할인 후</th>
<th scope="col">멤버십 할인 시**</th>
</tr>
</thead>
<tbody>
<tr>
<th rowspan="5" scope="row">KT 365 폰케어*<br/>
			(서비스형 5종)</th>
<td>폴드</td>
<td rowspan="4">분실/<br/>
			도난/<br/>
			파손</td>
<td>갤럭시 폴드</td>
<td>14,000원</td>
<td>8,500원</td>
<td>4,000원</td>
</tr>
<tr>
<td>VVIP</td>
<td title="상승">100만원↑</td>
<td>10,500원</td>
<td>5,000원</td>
<td>500원</td>
</tr>
<tr>
<td>고급</td>
<td title="상승">60만원↑</td>
<td>7,500원</td>
<td>2,000원</td>
<td class="deducted" rowspan="3">무료</td>
</tr>
<tr>
<td>일반</td>
<td>제한 없음</td>
<td>6,500원</td>
<td class="brline-tp0">1,000원</td>
</tr>
<tr>
<td>파손</td>
<td>파손</td>
<td>제한 없음</td>
<td>5,900원</td>
<td class="brline-tp0">400원</td>
</tr>
<tr>
<th rowspan="2" scope="row">KT 365<br/>
			폰케어 i17***</th>
<td>플러스</td>
<td>분실/파손</td>
<td rowspan="2">아이폰17<br/>
			(17, 17 Air, 17 Pro, 17 Pro Max)</td>
<td>11,000원</td>
<td>5,500원</td>
<td>1,000원</td>
</tr>
<tr>
<td>파손</td>
<td>파손</td>
<td>5,500원</td>
<td class="pdt-bl" colspan="2">무료</td>
</tr>
</tbody>
</table>
<style type="text/css">.picode-1674-fte-area {width:1080px;margin:0 auto;}
        .picode-1674-fte-bg-column {margin:93px 0 0 0;padding:56px 0 60px;background:#F4F7F9;}

        .picode-1674-c-heading {display:flex;justify-content:center;align-items:center;margin:40px 0 0 0;padding:0 !important;font-size:36px !important;font-weight:300;line-height:1.4 !important;}
        .picode-1674-c-heading .bold {font-weight:700;}
        .picode-1674-c-heading .icon-star {position:absolute;top:-10px;right:-50px;}

        .picode-1674-c-heading .line {z-index:1;position:relative;padding:0 5px;}
        .picode-1674-c-heading .line:after {content:'';z-index:-1;position:absolute;bottom:2px;left:0;width:100%;height:18px;border-radius:100px;background:#D3FFFC;}

        .picode-1674-c-heading .icon-pfinger {margin:0 12px 0 0;}

        .picode-1674-s-heading {display:block;margin:34px 0 0 0;color:#222;font-size:24px;font-weight:500;text-align:left;}

        .picode-1674-top-banner {position:relative;margin:24px 0 0 0;font-size:0;}
        .picode-1674-top-banner .btn {position:absolute;bottom:42px;left:177px;width:183px;height:36px;}

        .picode-1674-tbl {margin:16px 0 0 0;border-bottom:1px solid #D5D5D5;font-size:14px;word-break:keep-all;overflow-wrap:break-word;text-align:center;}
        .picode-1674-tbl thead th {padding:16px 5px;border-left:1px solid #5A5A5A;background:#000;color:#fff;font-weight:500;}
        .picode-1674-tbl tbody th {padding:16px 5px;border-top:1px solid #D5D5D5;border-left:1px solid #D5D5D5;background:#EFEFEF;font-weight:400;}
        .picode-1674-tbl tbody td {padding:16px 5px;border-top:1px solid #D5D5D5;border-left:1px solid #D5D5D5;background:#fff;}
        .picode-1674-tbl tbody td:last-child {border-right:1px solid #D5D5D5;}
        .picode-1674-tbl tbody td.bg-tp1 {background:#FAEBEB;}
        .picode-1674-tbl tbody td.bg-tp2 {background:#CEE8FB;}
        .picode-1674-tbl tbody td.brline-tp0 {border-right:0;}

        .picode-1674-tbl.mt-tp1 {margin:48px 0 0 0;}
        .picode-1674-tbl.center-tp1 {text-align:center;}

        .picode-1674-dot-list {margin:14px 0 0 0;font-size:16px;text-align:left;}
        .picode-1674-dot-list > li {position:relative;padding:0 0 0 13px;}
        .picode-1674-dot-list > li:before {content:'';position:absolute;top:10px;left:0;width:3px;height:3px;border-radius:50%;background:#000;}
        .picode-1674-dot-list > li + li {margin:8px 0 0 0;}

        .picode-1674-dot-list li .picode-1674-desh-list {margin:4px 0 0 0;}
        .picode-1674-dot-list li .picode-1674-desh-list > li {position:relative;padding:0 0 0 13px;}
        .picode-1674-dot-list li .picode-1674-desh-list > li:before {content:'';position:absolute;top:11px;left:0;width:5px;height:1px;background:#000;}
        .picode-1674-dot-list li .picode-1674-desh-list > li + li {margin:8px 0 0 0;}

        .picode-1674-btn-groups {margin:24px 0 0 0;text-align:center;}
        .picode-1674-btn-column {display:inline-block;padding:10px 26px;border-radius:10px;background:#5DDFDE;color:#000;font-size:24px;font-weight:500;letter-spacing:-1.2px;}

        .picode-1674-note {margin:8px 0 0 0;font-weight:300;text-align:left;}
        .picode-1674-note.first {margin:14px 0 0 0;}
        .picode-1674-note.right-tp1 {text-align:right;}

        .N-pdt-num-list li .N-pdt-noted-list {margin:5px 0 0 0;}
        .N-pdt-num-list li .N-pdt-noted-list li {margin:5px 0 0 0;text-indent:0;}

        .picode-1674-fte-top-tt {margin:25px 0 0 0;padding:0 0 0 18px;text-indent:-18px;text-align:left;}
        .picode-1674-fte-top-tt.mt-tp1 {margin:20px 0 0 0;}
</style>
<style type="text/css">.N-pdt-choice-heading {
            display: block;
            margin: 81px 0 0 0;
            font-family: 'NSB';
            font-size: 42px;
            text-align: center;asdasd
            letter-spacing: -2.1px;
        }

        .N-pdt-choice-heading .line {
            z-index: 1;
            position: relative;
            padding: 0 10px;
        }

        .N-pdt-choice-heading .line:before {
            content: '';
            position: absolute;
            top: -16px;
            left: -24px;
            width: 41px;
            height: 48px;
            background: url('/static/prodetail/1500/common/itemForte/images/icon_N_star.png') no-repeat 0 0;
        }

        .N-pdt-choice-heading .line:after {
            content: '';
            z-index: -1;
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 20px;
            border-radius: 20px;
            background: #21FFF0;
            opacity: 0.2;
        }

        .N-pdt-choice-btn-area {
            margin: 26px 0 0 0;
            text-align: center;
        }

        .N-pdt-choice-btn-column {
            display: inline-block;
            min-width: 540px;
            height: 58px;
            padding: 0 5px;
            border-radius: 10px;
            background: #5DDFDE;
            color: #000;
            font-family: 'NSM';
            font-size: 24px;
            text-align: center;
            line-height: 58px;
            letter-spacing: -1.3px;
        }

        .N-pdt-choice-tbl {
            margin: 58px 0 0 0;
            border-bottom: 1px solid #D5D5D5;
            border-right: 1px solid #D5D5D5;
            background:#fff;
        }

        .N-pdt-choice-tbl thead th {
            padding: 10px;
            border-top: 1px solid #D5D5D5;
            background: #000;
            color: #fff;
            font-family: 'NSM';
            font-weight: normal;
            font-size: 18px;
        }

        .N-pdt-choice-tbl tbody th.brr {
            border-right: 1px solid #D5D5D5;
        }

        .N-pdt-choice-tbl tbody th,
        .N-pdt-choice-tbl tbody td {
            padding: 10px;
        }

        .N-pdt-choice-tbl thead th+th {
            border-left: 1px solid #D5D5D5;
        }

        .N-pdt-choice-tbl tbody th {
            border-top: 1px solid #D5D5D5;
            background: #efefef;
            font-weight: normal;
        }

        .N-pdt-choice-tbl tbody td {
            padding: 10px;
            border-top: 1px solid #D5D5D5;
            border-left: 1px solid #D5D5D5;
            color: #000;
            font-size: 16px;
            text-align: center;
        }

        .N-pdt-choice-tbl tbody td.deducted {
            background: #FAEBEB;
        }

        .N-pdt-choice-tbl tbody td.sale {
            background: #EBF4FA;
        }

        .N-pdt-choice-note {
            margin: 14px 0 0 0;
            font-family: 'NSL';
            font-size: 16px;
            text-align: right;
        }
</style>
<p class="picode-1674-note">* 2025년 1월 20일 출시한 ‘KT 365 폰케어’ 서비스형 상품 5종에 한하여 초이스 할인이 적용 됩니다.</p>
<p class="picode-1674-note">** 초이스 더블 이용 시, 단말 보험 월정액 멤버십 할인(월 최대 4,500원)</p>
<p class="picode-1674-note">*** 가입 가능 기간 : 2025년 9월 19일 ~ 2025년 11월 30일</p>
</div>
</div>
<div class="inner">
<div class="N-pdt-accordion-section">
<div class="N-pdt-accordion-column">
<h2 class="seo-improve-heading"><button class="N-pdt-accordion-tit opener" onclick="KT_product_trackClicks('KT-개인_상품_모바일_모바일_요금제','^KT-개인_상품_모바일_모바일_요금제_초이스_더블^아코디언^요금안내_열기');">요금안내</button></h2>
<div class="N-pdt-accordion-cont">
<ul aria-label="요금 기준 연령 선택" class="N-picode-rate-tab-group" data-pktcode-js="rate-tab" role="tablist">
<li role="presentation"><button aria-controls="N-rate-table-panel" aria-selected="true" class="btn-column" data-age="base" id="N-rate-tab-base" role="tab" type="button">기본제공</button></li>
<li role="presentation"><button aria-controls="N-rate-table-panel" aria-selected="false" class="btn-column" data-age="y" id="N-rate-tab-y" role="tab" type="button">Y덤(만 19세 ~ 만 34세)</button></li>
<li role="presentation"><button aria-controls="N-rate-table-panel" aria-selected="false" class="btn-column" data-age="65" id="N-rate-tab-65" role="tab" type="button">65+덤(만 65세 ~ 만 74세)</button></li>
<li role="presentation"><button aria-controls="N-rate-table-panel" aria-selected="false" class="btn-column" data-age="75" id="N-rate-tab-75" role="tab" type="button">75+덤(만 75세 ~)</button></li>
</ul>
<p class="N-pdt-tbl-desc">부가세가 포함된 실제 지불금액입니다.</p>
<div aria-labelledby="pkt-rate-tab-base" id="N-rate-table-panel" role="tabpanel">
<table class="N-pdt-tbl-plan">
<caption class="invisible">표</caption>
</table>
</div>
<ul class="N-pdt-num-list">
<li>1) 단말보험 월정액을 최대 4,500원 한도 내에서(플러스 서비스료 제외) 멤버십 할인 가능합니다.
	<ul class="N-pdt-noted-list">
<li>다른 요금제로 변경 시 해당 시점부터 일할 계산되어 요금이 발생합니다.</li>
</ul>
</li>
</ul>
<ul class="N-pdt-list">
<li>본 요금제 가입 후 365 폰케어 단말 보험 상품을 별도로 가입하셔야 할인혜택이 적용되며, 할인 대상 상품은 추후 변경될 수 있습니다. <a class="N-pdt-btn-is" href="https://product.kt.com/wDic/productDetail.do?ItemCode=1604">자세히 보기</a></li>
<li>본 요금제 가입 후 월 말까지 유지 시 단말 보험 할인이 적용되며, 월 중 요금제 변경/정지/해지 시 단말 보험 월정액이 정상 청구됩니다.</li>
<li>음성통화/문자는 기본제공 되며, 영상/부가통화는 300분이 제공됩니다.</li>
<li>초이스 혜택은 제휴사 사정에 따라 변경 될 수 있습니다.</li>